# Generated by Django 5.0.1 on 2025-11-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='ID проекта')),
                ('student_id', models.IntegerField(verbose_name='ID студента')),
                ('teacher_id', models.IntegerField(blank=True, null=True, verbose_name='ID преподавателя')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('reviewing', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено'), ('revision', 'Требует доработки')], default='pending', max_length=20, verbose_name='Статус')),
                ('repository_url', models.URLField(blank=True, verbose_name='URL репозитория')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL демо')),
                ('documentation_url', models.URLField(blank=True, verbose_name='URL документации')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('max_grade', models.IntegerField(default=100, verbose_name='Максимальная оценка')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сдача работы',
                'verbose_name_plural': 'Сдачи работ',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField(verbose_name='ID проверяющего')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('file_url', models.URLField(verbose_name='URL файла')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.submission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
