# Generated by Django 5.0.1 on 2025-11-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID пользователя')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL аватара')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Университет')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Группа')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='intermediate', max_length=20, verbose_name='Уровень')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
